" Vim config for servers

set tabstop=4
set shiftwidth=4
set expandtab
let mapleader = " "
set backspace=indent,eol,start

" Ui settings
syntax on

" Remaps

" Ex filemanager
nnoremap <Leader>f :Ex<CR>

" Buffer management
nnoremap <leader>k :bnext<CR>
nnoremap <leader>j :bprev<CR>
nnoremap <leader>b :buffers<CR>

" Completion tab
inoremap <expr> <Tab> SmartTab()

" Functions
function! SmartTab()
    if col('.') > 1 && getline('.')[col('.') - 2] !~ '\s'
        return "\<C-n>"
    else
        return "\<Tab>"
    endif
endfunction
